# 1. Create a 3x3x3 array with random values 

In [5]:
import numpy as np
arr = np.random.random((3,3,3))
print(arr)

[[[0.59147383 0.09466622 0.12599856]
  [0.56203865 0.61173768 0.75069201]
  [0.30704306 0.61095676 0.84977478]]

 [[0.60645753 0.00909408 0.37399412]
  [0.70756701 0.97284488 0.18886859]
  [0.57751988 0.4152203  0.24377069]]

 [[0.26257864 0.4259509  0.66223089]
  [0.53682049 0.99892737 0.21251857]
  [0.45301657 0.42902936 0.56079814]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [7]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [8]:
import numpy as np
x = np.ones((3,3))
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [10]:
import numpy as np
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.30756819 0.07518876 0.82807071 0.76427968 0.10652842]
 [0.71887283 0.7583969  0.63414234 0.60516468 0.92585566]
 [0.16266387 0.60379597 0.89138627 0.25941269 0.00839914]
 [0.27401804 0.35383314 0.77619741 0.50463833 0.84656957]
 [0.64063689 0.40732471 0.31696147 0.85947291 0.85947701]]
After normalization:
[[0.32608526 0.07279868 0.89341735 0.82388704 0.10695797]
 [0.77439494 0.81747498 0.68204125 0.65045648 1.        ]
 [0.16814391 0.64896462 0.9624294  0.27359721 0.        ]
 [0.28951661 0.37651266 0.83687701 0.54088578 0.91358054]
 [0.68912012 0.43481686 0.33632366 0.9276448  0.92764926]]


# 5.  How to find common values between two arrays?

In [11]:
import numpy as np
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]


# 6.How to get the dates of yesterday, today and tomorrow?

In [12]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-25
Today:  2020-07-26
Tomorrow:  2020-07-27


# 7. Consider two random array A and B, check if they are equal

In [13]:
import numpy as np
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[0 1 0 0 0 0]
Second array:
[1 0 1 1 0 1]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [16]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[0.06345071 0.68844498 0.01044621 0.51583452 0.65604734 0.28796022
 0.4258834  0.35395331 0.83869606 0.49866009]
Maximum value replaced by 0:
[0.06345071 0.68844498 0.01044621 0.51583452 0.65604734 0.28796022
 0.4258834  0.35395331 0.         0.49866009]


# 9. How to print all the values of an array?

In [20]:
import numpy as np
#np.set_printoptions(threshold=np.nan)
x = np.random.random((4, 4))
print(x)

[[0.70309702 0.29565693 0.15540323 0.21814948]
 [0.93329387 0.3683224  0.09671751 0.96960863]
 [0.13624493 0.63200635 0.07723975 0.60523467]
 [0.03921547 0.42368234 0.89381507 0.13728552]]


# 10.Subtract the mean of each row of a matrix

In [48]:
print("Original matrix:\n")
X = np.random.random((5,5))
print(X)
print("After subtracting with mean:\n")
Y = X - X.mean(axis=1,keepdims=True)
print(Y)

Original matrix:

[[0.98077227 0.44875021 0.70422847 0.5935328  0.27422167]
 [0.67170787 0.85490916 0.63200135 0.4562475  0.77501421]
 [0.89704008 0.65642711 0.38665934 0.45680458 0.09849375]
 [0.16197724 0.84786097 0.10063605 0.74691388 0.56292553]
 [0.25967515 0.04895479 0.64812864 0.02678302 0.2104916 ]]
After subtracting with mean:

[[ 0.38047119 -0.15155088  0.10392739 -0.00676828 -0.32607942]
 [-0.00626815  0.17693314 -0.04597467 -0.22172851  0.09703819]
 [ 0.3979551   0.15734214 -0.11242563 -0.0422804  -0.40059123]
 [-0.32208549  0.36379824 -0.38342669  0.26285115  0.07886279]
 [ 0.02086851 -0.18985185  0.409322   -0.21202362 -0.02831504]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [56]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
print(Z)
Z += np.bincount(I, minlength=len(Z))
print(I)
print("above",Z)


np.add.at(Z, I, 1)
print(Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[4 9 7 6 4 0 3 8 7 0 7 6 5 2 5 1 7 9 5 5]
above [3. 2. 2. 2. 3. 5. 3. 5. 2. 3.]
[5. 3. 3. 3. 5. 9. 5. 9. 3. 5.]


# 12.How to get the diagonal of a dot product?

In [57]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([1.17681565, 2.03555757, 1.5966771 , 0.84685336, 1.42491647])

# 13.How to find the most frequent value in an array?

In [59]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

9


# 14.How to get the n largest values of an array

In [60]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9995 9999 9996 9998 9997]


# 15.How to create a record array from a regular array?

In [26]:
import numpy as np
person_data_def = [('name','U10'),('age','i8')]
person_rec_array = np.rec.array([("Sow",23),("Dee",34)],dtype=person_data_def)
print(person_rec_array[0].age)

23
